# Generated by Django 2.2 on 2020-02-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletable',
            name='phone_number',
            field=models.CharField(max_length=256),
        ),
    ]
