# Generated by Django 2.2 on 2020-02-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand', models.CharField(max_length=256, verbose_name='نام برند')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=256, verbose_name='نام دسته')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('inventory', models.PositiveIntegerField(verbose_name='تعداد موجود')),
                ('img', models.ImageField(upload_to='', verbose_name='تصویر محصول')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.Brand', verbose_name='نام برند')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sub', models.CharField(max_length=256, verbose_name='نام زیر دسته')),
                ('name_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='contentapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('parent_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='tv', serialize=False, to='contentapp.Content')),
                ('weight', models.FloatField(help_text='according of kg', verbose_name='وزن')),
                ('dimensions', models.CharField(help_text='according of this pattern a*b*c', max_length=256, verbose_name='ابعاد')),
                ('hdmi', models.BooleanField(verbose_name='دارای پورت hdmi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.Category', verbose_name='نام دسته')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contentapp.SubCategory', verbose_name='نام زیر دسته')),
            ],
            bases=('contentapp.content',),
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('parent_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ref', serialize=False, to='contentapp.Content')),
                ('capacity', models.FloatField(help_text='according of kg', verbose_name='ظرفیت یخچال')),
                ('floor_number', models.IntegerField(verbose_name='تعداد طبقات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.Category', verbose_name='نام دسته')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contentapp.SubCategory', verbose_name='نام زیر دسته')),
            ],
            bases=('contentapp.content',),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('parent_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='mobile', serialize=False, to='contentapp.Content')),
                ('weight', models.FloatField(help_text='according of kg', verbose_name='وزن')),
                ('ram', models.IntegerField(help_text='according of GB')),
                ('camera', models.BooleanField(verbose_name='دارای دوربین است')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.Category', verbose_name='نام دسته')),
            ],
            bases=('contentapp.content',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('parent_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='laptop', serialize=False, to='contentapp.Content')),
                ('weight', models.FloatField(help_text='according of kg', verbose_name='وزن')),
                ('cpu', models.CharField(max_length=256)),
                ('cache', models.IntegerField(help_text='according of MB')),
                ('webcame', models.BooleanField(verbose_name='دارای وب کم هست')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.Category', verbose_name='نام دسته')),
            ],
            bases=('contentapp.content',),
        ),
    ]
