# Generated by Django 2.2 on 2020-01-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contentapp.Content')),
                ('img', models.ImageField(upload_to='')),
                ('capacity', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.Category')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contentapp.SubCategory')),
            ],
            bases=('contentapp.content',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contentapp.Content')),
                ('img', models.ImageField(upload_to='')),
                ('weight', models.IntegerField()),
                ('cpu', models.CharField(max_length=256)),
                ('cache', models.IntegerField()),
                ('webcame', models.BooleanField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.Category')),
            ],
            bases=('contentapp.content',),
        ),
    ]
