# Generated by Django 2.2 on 2019-12-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('first_choice', models.CharField(max_length=500)),
                ('secound_choice', models.CharField(max_length=500)),
                ('third_choice', models.CharField(max_length=500)),
                ('fourth_choice', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=1)),
            ],
        ),
    ]
