# Generated by Django 2.2 on 2019-12-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allquestion',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='allquestion',
            name='first_choice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='allquestion',
            name='fourth_choice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='allquestion',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='allquestion',
            name='secound_choice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='allquestion',
            name='third_choice',
            field=models.TextField(),
        ),
    ]
