# Generated by Django 2.2 on 2020-02-07 08:19

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginapp', '0006_auto_20200205_2227'),
        ('contentapp', '0002_auto_20200203_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('wc', 'wc'), ('wb', 'wb'), ('fb', 'fb')], default='wc', max_length=10)),
                ('supplier_status', models.CharField(choices=[('uv', 'uv'), ('v', 'v')], default='uv', max_length=10)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', related_query_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('c', 'c'), ('b', 'b')], default='c', max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', related_query_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
