# Generated by Django 2.2 on 2020-02-03 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contentapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('c', 'c'), ('b', 'b')], default='c', max_length=10)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', related_query_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
