# Generated by Django 2.2 on 2020-02-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('wc', 'wc'), ('wb', 'wb'), ('fb', 'fb')], default='wc', max_length=10),
        ),
    ]
