# Generated by Django 2.2 on 2019-12-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='wirter',
            field=models.ManyToManyField(related_name='books', related_query_name='books', to='app1.Writer'),
        ),
    ]
